[2025-04-21 06:03:25,019] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:03:58,035] INFO django.server "GET /companies/company/list/ HTTP/1.1" 200 6814
[2025-04-21 06:04:02,564] INFO django.server "GET /patient/list/ HTTP/1.1" 200 6407
[2025-04-21 06:04:03,747] INFO django.server "GET /patient/new/ HTTP/1.1" 200 4989
[2025-04-21 06:04:16,754] INFO django.server "POST /patient/new/ HTTP/1.1" 200 5245
[2025-04-21 06:04:18,317] INFO django.server "GET / HTTP/1.1" 200 5826
[2025-04-21 06:06:56,659] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\patients\views.py changed, reloading.
[2025-04-21 06:06:57,063] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:08:01,605] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\patients\views.py changed, reloading.
[2025-04-21 06:08:02,090] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:08:15,719] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\patients\views.py changed, reloading.
[2025-04-21 06:08:16,175] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:08:52,212] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\patients\views.py changed, reloading.
[2025-04-21 06:08:52,620] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:08:55,724] INFO django.server "GET / HTTP/1.1" 200 5826
[2025-04-21 06:08:56,911] INFO django.server "GET /patient/new/ HTTP/1.1" 200 4989
[2025-04-21 06:09:16,265] INFO mdc_app Patient CREATED by user='mapleshield': id=10, name=CATHERINE MARIANO
[2025-04-21 06:09:16,268] INFO django.server "POST /patient/new/ HTTP/1.1" 200 5249
[2025-04-21 06:09:17,430] INFO django.server "GET / HTTP/1.1" 200 5826
[2025-04-21 06:09:56,392] INFO django.server "GET /patient/new/ HTTP/1.1" 200 4989
[2025-04-21 06:09:58,738] INFO django.server "GET /patient/list/ HTTP/1.1" 200 7862
[2025-04-21 06:10:01,904] INFO django.server "GET /patient/10/edit/ HTTP/1.1" 200 5016
[2025-04-21 06:12:27,327] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\patients\views.py changed, reloading.
[2025-04-21 06:12:27,751] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:12:43,147] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\patients\views.py changed, reloading.
[2025-04-21 06:12:43,501] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:14:19,075] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\patients\views.py changed, reloading.
[2025-04-21 06:14:19,488] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:14:23,257] INFO django.server "POST /patient/10/edit/ HTTP/1.1" 302 0
[2025-04-21 06:14:23,270] INFO django.server "GET /patient/list/ HTTP/1.1" 200 7862
[2025-04-21 06:14:40,289] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:14:42,483] INFO django.server "GET /patient/list/ HTTP/1.1" 200 7862
[2025-04-21 06:14:45,888] INFO django.server "GET /patient/10/edit/ HTTP/1.1" 200 5019
[2025-04-21 06:14:53,496] INFO django.server "POST /patient/10/edit/ HTTP/1.1" 302 0
[2025-04-21 06:14:53,504] INFO django.server "GET /patient/list/ HTTP/1.1" 200 7862
[2025-04-21 06:16:04,469] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\mdc_app\settings.py changed, reloading.
[2025-04-21 06:16:04,929] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:16:23,868] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:16:30,409] INFO django.server "GET /patient/9/edit/ HTTP/1.1" 200 5013
[2025-04-21 06:16:37,490] INFO mdc_app Patient UPDATED by user='mapleshield' (id=9): 'middle_name': 'UY' â†’ 'CRUZ'
[2025-04-21 06:16:37,491] INFO django.server "POST /patient/9/edit/ HTTP/1.1" 302 0
[2025-04-21 06:16:37,503] INFO django.server "GET /patient/list/ HTTP/1.1" 200 7862
[2025-04-21 06:19:31,965] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\patients\views.py changed, reloading.
[2025-04-21 06:19:32,359] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:20:23,540] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 14583
[2025-04-21 06:21:02,493] INFO django.server "GET /patient/list/ HTTP/1.1" 200 8226
[2025-04-21 06:21:06,705] ERROR django.request Internal Server Error: /patient/list/
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\list.py", line 158, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\patients\views.py", line 48, in get_queryset
    Q(first_name__icontains=q) |
    ^
NameError: name 'Q' is not defined
[2025-04-21 06:21:06,707] ERROR django.server "GET /patient/list/?q=BEA HTTP/1.1" 500 92888
[2025-04-21 06:21:55,690] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\patients\views.py changed, reloading.
[2025-04-21 06:21:56,112] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:21:57,434] INFO django.server "GET /patient/list/ HTTP/1.1" 200 8226
[2025-04-21 06:22:01,406] INFO django.server "GET /patient/list/?q=BEA HTTP/1.1" 200 6860
[2025-04-21 06:22:07,928] INFO django.server "GET /patient/list/?q=ALBERT HTTP/1.1" 200 6866
[2025-04-21 06:22:13,158] INFO django.server "GET /patient/list/?q=7 HTTP/1.1" 200 5887
[2025-04-21 06:22:15,808] INFO django.server "GET /patient/list/ HTTP/1.1" 200 8226
[2025-04-21 06:22:19,544] INFO django.server "GET /patient/list/?q=8 HTTP/1.1" 200 6858
[2025-04-21 06:22:20,875] INFO django.server "GET /patient/list/ HTTP/1.1" 200 8226
[2025-04-21 06:22:25,718] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 14583
[2025-04-21 06:25:18,522] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\transactions\views.py changed, reloading.
[2025-04-21 06:25:18,952] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:25:47,825] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\transactions\views.py changed, reloading.
[2025-04-21 06:25:48,299] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 06:26:14,630] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 14920
[2025-04-21 06:26:32,952] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 14963
[2025-04-21 06:26:42,043] INFO django.server "GET /transactions/transaction/list/?q=17 HTTP/1.1" 200 13494
[2025-04-21 06:26:47,245] INFO django.server "GET /transactions/transaction/list/?q=BEA HTTP/1.1" 200 15073
[2025-04-21 06:27:06,204] INFO django.server "GET /patient/list/ HTTP/1.1" 200 8226
[2025-04-21 06:27:09,154] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 14963
[2025-04-21 06:27:10,401] INFO django.server "GET / HTTP/1.1" 200 5826
[2025-04-21 06:27:15,188] INFO django.server "GET /transactions/transaction/active_list/ HTTP/1.1" 200 11405
[2025-04-21 06:28:11,183] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 14963
[2025-04-21 06:28:16,282] INFO django.server "GET /transactions/transaction/list/?q=18 HTTP/1.1" 200 13506
[2025-04-21 06:28:18,114] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 14963
[2025-04-21 06:33:38,864] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 14963
[2025-04-21 07:00:37,016] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 14963
[2025-04-21 07:00:54,751] INFO django.server "GET / HTTP/1.1" 200 5826
[2025-04-21 07:39:17,900] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 60698
[2025-04-21 07:46:16,607] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 14963
[2025-04-21 07:47:03,034] INFO django.server "GET /companies/company/list/ HTTP/1.1" 200 6814
[2025-04-21 07:47:05,521] INFO django.server "GET / HTTP/1.1" 200 5826
[2025-04-21 07:47:22,600] INFO django.server "GET / HTTP/1.1" 200 5826
[2025-04-21 07:51:36,748] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 07:51:37,957] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 60698
[2025-04-21 07:51:51,344] INFO django.server "GET /transactions/ajax/get-company-peme-rate/4/ HTTP/1.1" 200 18
[2025-04-21 07:52:08,223] INFO django.server "POST /transactions/transaction/new/ HTTP/1.1" 302 0
[2025-04-21 07:52:08,257] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 16517
[2025-04-21 07:56:47,019] INFO django.server "GET /tests/test/list/ HTTP/1.1" 200 48478
[2025-04-21 07:56:48,969] INFO django.server "GET /tests/test/new/ HTTP/1.1" 200 3381
[2025-04-21 07:57:12,079] INFO django.server "GET /tests/test/39/edit/ HTTP/1.1" 200 3394
[2025-04-21 08:00:56,745] INFO django.server "GET /companies/company/list/ HTTP/1.1" 200 6814
[2025-04-21 08:01:02,838] INFO django.server "GET /companies/company/list/ HTTP/1.1" 200 6814
[2025-04-21 08:01:08,582] INFO django.server "GET /companies/company/list/ HTTP/1.1" 200 6814
[2025-04-21 08:01:09,498] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 08:01:10,603] INFO django.server "GET /companies/company/new/ HTTP/1.1" 200 5114
[2025-04-21 08:04:36,150] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 08:04:37,455] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 60698
[2025-04-21 08:07:05,708] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 16517
[2025-04-21 08:07:08,417] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 60698
[2025-04-21 08:07:12,384] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 16517
[2025-04-21 08:09:18,049] INFO django.server "GET /patient/list/ HTTP/1.1" 200 8226
[2025-04-21 08:09:52,119] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 16517
[2025-04-21 08:09:54,913] INFO django.server "GET /companies/company/list/ HTTP/1.1" 200 6814
[2025-04-21 08:09:56,817] INFO django.server "GET /companies/company/5/ HTTP/1.1" 200 6565
[2025-04-21 08:09:59,619] INFO django.server "GET /companies/company/list/ HTTP/1.1" 200 6814
[2025-04-21 08:10:01,676] INFO django.server "GET /companies/company/4/ HTTP/1.1" 200 7544
[2025-04-21 08:10:06,094] INFO django.server "GET /companies/company/4/generate_statement/?month=2025-04 HTTP/1.1" 200 3135
[2025-04-21 08:11:30,526] INFO django.server "GET /patient/list/ HTTP/1.1" 200 8226
[2025-04-21 08:12:53,719] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 08:13:30,879] INFO django.server "GET /patient/list/ HTTP/1.1" 200 8226
[2025-04-21 08:13:32,207] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 16517
[2025-04-21 08:13:47,511] INFO django.server "GET /transactions/transaction/19/ HTTP/1.1" 200 5418
[2025-04-21 08:15:45,517] INFO django.server "GET /transactions/transaction/19/ HTTP/1.1" 200 5418
[2025-04-21 08:16:32,488] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 08:58:12,450] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 09:19:22,327] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\transactions\models.py changed, reloading.
[2025-04-21 09:19:22,909] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-21 09:19:35,298] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 60736
[2025-04-21 09:44:02,162] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 09:44:05,219] INFO django.server "GET /companies/company/list/ HTTP/1.1" 200 6992
[2025-04-21 10:09:39,523] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 10:09:43,105] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 60736
[2025-04-21 10:09:53,509] INFO django.server "GET /transactions/ajax/get-company-peme-rate/7/ HTTP/1.1" 200 16
[2025-04-21 10:10:12,711] INFO django.server "POST /transactions/transaction/new/ HTTP/1.1" 302 0
[2025-04-21 10:10:12,771] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 18075
[2025-04-21 10:11:22,566] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 18075
[2025-04-21 10:11:25,085] INFO django.server "GET /transactions/transaction/20/edit/ HTTP/1.1" 200 60778
[2025-04-21 10:11:27,146] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 18075
[2025-04-21 10:11:29,941] INFO django.server "GET /transactions/transaction/20/edit/ HTTP/1.1" 200 60778
[2025-04-21 10:11:34,085] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 18075
[2025-04-21 10:11:35,032] INFO django.server "GET /transactions/transaction/20/ HTTP/1.1" 200 5420
[2025-04-21 10:14:25,761] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 10:14:29,299] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67602
[2025-04-21 10:14:37,985] INFO django.server "GET /transactions/ajax/get-company-peme-rate/5/ HTTP/1.1" 200 18
[2025-04-21 10:16:51,432] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67295
[2025-04-21 11:18:55,328] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 11:20:07,666] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 11:20:09,787] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 18075
[2025-04-21 11:20:11,190] INFO django.server "GET /patient/list/ HTTP/1.1" 200 8226
[2025-04-21 11:20:13,091] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-21 11:20:13,794] INFO django.server "GET /patient/list/ HTTP/1.1" 200 8226
[2025-04-21 11:20:14,598] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-22 04:38:13,890] INFO django.server "GET / HTTP/1.1" 200 5896
[2025-04-22 04:38:13,900] INFO django.server "GET /static/images/mdc_logo.jpg HTTP/1.1" 304 0
[2025-04-22 04:38:14,841] WARNING django.request Not Found: /favicon.ico
[2025-04-22 04:38:14,841] WARNING django.server "GET /favicon.ico HTTP/1.1" 404 4596
[2025-04-22 04:38:29,375] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67295
[2025-04-22 04:38:47,755] INFO django.server "GET /transactions/ajax/get-company-peme-rate/4/ HTTP/1.1" 200 18
[2025-04-22 04:39:09,526] INFO django.server "POST /transactions/transaction/new/ HTTP/1.1" 302 0
[2025-04-22 04:39:09,540] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 19679
[2025-04-22 04:39:17,263] INFO django.server "GET /transactions/transaction/21/ HTTP/1.1" 200 5578
[2025-04-22 04:41:29,367] INFO django.server "GET /transactions/transaction/21/ HTTP/1.1" 200 5578
[2025-04-22 04:41:31,771] INFO django.server "GET /transactions/transaction/list/ HTTP/1.1" 200 19682
[2025-04-22 04:41:38,267] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67295
[2025-04-22 04:50:40,263] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\mdc_app\settings.py changed, reloading.
[2025-04-22 04:50:40,753] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 04:51:02,803] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\models.py changed, reloading.
[2025-04-22 04:51:03,228] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 04:53:12,087] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\mdc_app\urls.py changed, reloading.
[2025-04-22 04:53:12,576] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 04:57:09,246] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\urls.py changed, reloading.
[2025-04-22 04:57:09,671] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 04:57:36,534] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 04:57:36,955] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 04:58:44,534] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\models.py changed, reloading.
[2025-04-22 04:58:44,959] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 04:58:51,387] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 04:58:51,768] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 05:00:39,945] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 05:00:40,338] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 05:03:39,488] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 05:06:53,553] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\models.py changed, reloading.
[2025-04-22 05:06:53,971] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 05:07:56,457] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\models.py changed, reloading.
[2025-04-22 05:07:56,960] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 05:10:13,228] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 05:10:19,713] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 05:10:22,451] ERROR django.request Internal Server Error: /setpackages/setpackages/list/
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: setpackages/setpackage_list.html, setpackages/setpackage_list.html
[2025-04-22 05:10:22,452] ERROR django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 500 90636
[2025-04-22 05:11:18,734] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2102
[2025-04-22 05:11:22,339] INFO django.server "GET /setpackages/setpackages/new/ HTTP/1.1" 200 2868
[2025-04-22 05:18:04,688] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 05:18:05,510] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2102
[2025-04-22 05:18:07,371] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2102
[2025-04-22 05:21:01,265] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2102
[2025-04-22 05:21:02,357] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2102
[2025-04-22 05:21:02,540] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2102
[2025-04-22 05:21:02,712] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2102
[2025-04-22 05:21:02,854] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2102
[2025-04-22 05:21:02,998] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2102
[2025-04-22 05:21:03,161] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2102
[2025-04-22 05:21:36,231] ERROR django.request Internal Server Error: /setpackages/setpackages/1/
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'setpackage_edit' not found. 'setpackage_edit' is not a valid view function or pattern name.
[2025-04-22 05:21:36,233] ERROR django.server "GET /setpackages/setpackages/1/ HTTP/1.1" 500 118996
[2025-04-22 05:23:27,700] ERROR django.request Internal Server Error: /setpackages/setpackages/list/
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'setpackage_new' not found. 'setpackage_new' is not a valid view function or pattern name.
[2025-04-22 05:23:27,701] ERROR django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 500 119119
[2025-04-22 05:23:57,360] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\urls.py changed, reloading.
[2025-04-22 05:23:57,799] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 05:24:05,934] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2074
[2025-04-22 05:25:09,999] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2074
[2025-04-22 05:27:56,394] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:28:58,326] ERROR django.request Internal Server Error: /setpackages/setpackages/1/
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'setpackage_edit' with arguments '('',)' not found. 1 pattern(s) tried: ['setpackages/setpackages/(?P<pk>[0-9]+)/edit/\\Z']
[2025-04-22 05:28:58,327] ERROR django.server "GET /setpackages/setpackages/1/ HTTP/1.1" 500 122396
[2025-04-22 05:33:15,201] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:17,196] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:17,363] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:17,544] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:17,704] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:18,022] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:18,180] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:18,404] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:18,575] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:18,804] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:18,936] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3478
[2025-04-22 05:33:31,325] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4022
[2025-04-22 05:33:39,671] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:33:41,309] ERROR django.request Internal Server Error: /setpackages/setpackages/3/
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'setpackage_edit' with arguments '('',)' not found. 1 pattern(s) tried: ['setpackages/setpackages/(?P<pk>[0-9]+)/edit/\\Z']
[2025-04-22 05:33:41,310] ERROR django.server "GET /setpackages/setpackages/3/ HTTP/1.1" 500 122588
[2025-04-22 05:36:13,560] ERROR django.request Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'setpackages_list' not found. 'setpackages_list' is not a valid view function or pattern name.
[2025-04-22 05:36:13,561] ERROR django.server "GET / HTTP/1.1" 500 175017
[2025-04-22 05:36:13,972] ERROR django.request Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'setpackages_list' not found. 'setpackages_list' is not a valid view function or pattern name.
[2025-04-22 05:36:13,973] ERROR django.server "GET / HTTP/1.1" 500 174743
[2025-04-22 05:36:57,025] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 05:36:58,457] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:36:59,988] INFO django.server "GET /setpackages/setpackages/4/ HTTP/1.1" 200 2489
[2025-04-22 05:37:07,624] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:37:09,788] INFO django.server "GET /setpackages/setpackages/3/ HTTP/1.1" 200 3095
[2025-04-22 05:37:18,646] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:37:58,084] INFO django.server "GET /setpackages/setpackages/3/ HTTP/1.1" 200 3095
[2025-04-22 05:37:59,598] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:38:00,501] INFO django.server "GET /setpackages/setpackages/1/ HTTP/1.1" 200 2490
[2025-04-22 05:38:05,929] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:38:07,230] INFO django.server "GET /setpackages/setpackages/2/ HTTP/1.1" 200 3095
[2025-04-22 05:38:08,416] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:39:14,377] INFO django.server "GET /setpackages/setpackages/4/ HTTP/1.1" 200 2489
[2025-04-22 05:39:19,157] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:40:17,043] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:40:18,137] INFO django.server "GET /setpackages/setpackages/4/ HTTP/1.1" 200 3095
[2025-04-22 05:40:19,623] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:40:20,900] INFO django.server "GET /setpackages/setpackages/1/ HTTP/1.1" 200 2490
[2025-04-22 05:40:21,839] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:40:25,471] INFO django.server "GET /setpackages/setpackages/2/ HTTP/1.1" 200 3095
[2025-04-22 05:40:31,663] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:40:37,218] INFO django.server "GET /setpackages/setpackages/1/ HTTP/1.1" 200 2490
[2025-04-22 05:40:39,814] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4566
[2025-04-22 05:45:15,979] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4578
[2025-04-22 05:45:22,180] ERROR django.request Internal Server Error: /setpackages/setpackages/1/delete/
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'setpackages_detail' not found. 'setpackages_detail' is not a valid view function or pattern name.
[2025-04-22 05:45:22,181] ERROR django.server "GET /setpackages/setpackages/1/delete/ HTTP/1.1" 500 118148
[2025-04-22 05:45:50,790] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 05:45:53,011] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4578
[2025-04-22 05:45:57,536] ERROR django.request Internal Server Error: /setpackages/setpackages/1/delete/
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'setpackage_detail' with arguments '('',)' not found. 1 pattern(s) tried: ['setpackages/setpackages/(?P<pk>[0-9]+)/\\Z']
[2025-04-22 05:45:57,537] ERROR django.server "GET /setpackages/setpackages/1/delete/ HTTP/1.1" 500 121259
[2025-04-22 05:46:09,183] INFO django.server "GET /setpackages/setpackages/3/ HTTP/1.1" 200 3095
[2025-04-22 05:46:13,256] INFO django.server "GET /setpackages/setpackages/4/ HTTP/1.1" 200 3095
[2025-04-22 05:46:16,466] INFO django.server "GET /setpackages/setpackages/4/ HTTP/1.1" 200 3095
[2025-04-22 05:46:36,028] INFO django.server "GET /setpackages/setpackages/4/ HTTP/1.1" 200 3100
[2025-04-22 05:47:00,971] INFO django.server "GET /setpackages/setpackages/4/ HTTP/1.1" 200 3123
[2025-04-22 05:47:42,655] INFO django.server "GET /setpackages/setpackages/4/ HTTP/1.1" 200 2985
[2025-04-22 05:47:54,342] ERROR django.request Internal Server Error: /setpackages/setpackages/4/delete/
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'setpackage_detail' with arguments '('',)' not found. 1 pattern(s) tried: ['setpackages/setpackages/(?P<pk>[0-9]+)/\\Z']
[2025-04-22 05:47:54,344] ERROR django.server "GET /setpackages/setpackages/4/delete/ HTTP/1.1" 500 121448
[2025-04-22 05:49:32,648] INFO django.server "GET /setpackages/setpackages/4/delete/ HTTP/1.1" 200 2101
[2025-04-22 05:49:37,405] INFO django.server "POST /setpackages/setpackages/4/delete/ HTTP/1.1" 302 0
[2025-04-22 05:49:37,418] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4029
[2025-04-22 05:49:42,138] INFO django.server "GET /setpackages/setpackages/1/delete/ HTTP/1.1" 200 2101
[2025-04-22 05:49:43,413] INFO django.server "POST /setpackages/setpackages/1/delete/ HTTP/1.1" 302 0
[2025-04-22 05:49:43,419] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3484
[2025-04-22 05:49:45,470] INFO django.server "GET /setpackages/setpackages/2/delete/ HTTP/1.1" 200 2101
[2025-04-22 05:49:46,392] INFO django.server "POST /setpackages/setpackages/2/delete/ HTTP/1.1" 302 0
[2025-04-22 05:49:46,407] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 2940
[2025-04-22 05:49:47,408] INFO django.server "GET /setpackages/setpackages/new/ HTTP/1.1" 200 2868
[2025-04-22 05:50:17,333] ERROR django.request Internal Server Error: /setpackages/setpackages/new/
Traceback (most recent call last):
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py", line 33, in form_valid
    setpackage_name__iexact=data['setpackage_name']
                            ~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'setpackage_name'
[2025-04-22 05:50:17,334] ERROR django.server "POST /setpackages/setpackages/new/ HTTP/1.1" 500 99055
[2025-04-22 05:54:54,537] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 05:54:54,987] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 05:54:58,816] INFO django.server "GET /setpackages/setpackages/new/ HTTP/1.1" 200 28223
[2025-04-22 05:55:23,549] INFO django.server "GET /setpackages/setpackages/new/ HTTP/1.1" 200 29614
[2025-04-22 05:56:16,759] INFO django.server "POST /setpackages/setpackages/new/ HTTP/1.1" 302 0
[2025-04-22 05:56:16,769] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3530
[2025-04-22 05:56:19,523] INFO django.server "GET /setpackages/setpackages/5/ HTTP/1.1" 200 3505
[2025-04-22 05:56:23,120] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3530
[2025-04-22 05:56:25,793] INFO django.server "GET /setpackages/setpackages/5/edit/ HTTP/1.1" 200 3303
[2025-04-22 05:57:46,941] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 05:57:47,325] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 05:57:52,142] INFO django.server "GET /setpackages/setpackages/5/edit/ HTTP/1.1" 200 29668
[2025-04-22 05:58:00,646] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 05:58:01,942] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3530
[2025-04-22 05:58:03,591] INFO django.server "GET /setpackages/setpackages/5/edit/ HTTP/1.1" 200 29668
[2025-04-22 05:59:48,144] INFO django.server "GET /setpackages/setpackages/5/edit/ HTTP/1.1" 200 34138
[2025-04-22 05:59:49,609] INFO django.server "GET /setpackages/setpackages/5/edit/ HTTP/1.1" 200 34138
[2025-04-22 05:59:55,814] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 05:59:56,984] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3530
[2025-04-22 05:59:58,670] INFO django.server "GET /setpackages/setpackages/3/edit/ HTTP/1.1" 200 34083
[2025-04-22 06:00:44,652] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 06:00:46,057] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3530
[2025-04-22 06:00:47,917] INFO django.server "GET /setpackages/setpackages/3/ HTTP/1.1" 200 2987
[2025-04-22 06:00:53,411] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3530
[2025-04-22 06:00:56,094] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 06:01:02,250] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 3530
[2025-04-22 06:01:16,961] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 06:01:34,431] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67295
[2025-04-22 06:05:12,765] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 06:05:13,175] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:05:34,944] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\urls.py changed, reloading.
[2025-04-22 06:05:35,356] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:06:13,371] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\urls.py changed, reloading.
[2025-04-22 06:06:13,759] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:06:18,218] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\urls.py changed, reloading.
[2025-04-22 06:06:18,630] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:07:54,646] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67969
[2025-04-22 06:07:54,664] WARNING django.request Not Found: /transactions/ajax/get-available-transaction-purposes/
[2025-04-22 06:07:54,664] WARNING django.server "GET /transactions/ajax/get-available-transaction-purposes/ HTTP/1.1" 404 6833
[2025-04-22 06:07:57,440] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67969
[2025-04-22 06:07:57,456] WARNING django.request Not Found: /transactions/ajax/get-available-transaction-purposes/
[2025-04-22 06:07:57,456] WARNING django.server "GET /transactions/ajax/get-available-transaction-purposes/ HTTP/1.1" 404 6833
[2025-04-22 06:07:57,947] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67969
[2025-04-22 06:07:57,961] WARNING django.request Not Found: /transactions/ajax/get-available-transaction-purposes/
[2025-04-22 06:07:57,962] WARNING django.server "GET /transactions/ajax/get-available-transaction-purposes/ HTTP/1.1" 404 6833
[2025-04-22 06:08:07,889] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67969
[2025-04-22 06:08:07,909] WARNING django.request Not Found: /transactions/ajax/get-available-transaction-purposes/
[2025-04-22 06:08:07,910] WARNING django.server "GET /transactions/ajax/get-available-transaction-purposes/ HTTP/1.1" 404 6833
[2025-04-22 06:08:08,424] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67969
[2025-04-22 06:08:08,443] WARNING django.request Not Found: /transactions/ajax/get-available-transaction-purposes/
[2025-04-22 06:08:08,443] WARNING django.server "GET /transactions/ajax/get-available-transaction-purposes/ HTTP/1.1" 404 6833
[2025-04-22 06:08:08,588] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67969
[2025-04-22 06:08:08,603] WARNING django.request Not Found: /transactions/ajax/get-available-transaction-purposes/
[2025-04-22 06:08:08,604] WARNING django.server "GET /transactions/ajax/get-available-transaction-purposes/ HTTP/1.1" 404 6833
[2025-04-22 06:08:55,665] WARNING django.request Not Found: /ajax/get-available-transaction-purposes/
[2025-04-22 06:08:55,665] WARNING django.server "GET /ajax/get-available-transaction-purposes/ HTTP/1.1" 404 4838
[2025-04-22 06:09:52,665] WARNING django.request Not Found: /ajax/get-available-transaction-purposes/
[2025-04-22 06:09:52,665] WARNING django.server "GET /ajax/get-available-transaction-purposes/ HTTP/1.1" 404 4838
[2025-04-22 06:09:53,601] WARNING django.request Not Found: /ajax/get-available-transaction-purposes/
[2025-04-22 06:09:53,601] WARNING django.server "GET /ajax/get-available-transaction-purposes/ HTTP/1.1" 404 4838
[2025-04-22 06:09:53,819] WARNING django.request Not Found: /ajax/get-available-transaction-purposes/
[2025-04-22 06:09:53,820] WARNING django.server "GET /ajax/get-available-transaction-purposes/ HTTP/1.1" 404 4838
[2025-04-22 06:09:56,005] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67968
[2025-04-22 06:09:56,021] INFO django.server "GET /setpackages/ajax/get-available-transaction-purposes/ HTTP/1.1" 200 40
[2025-04-22 06:12:22,105] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 06:12:22,537] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:12:39,151] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 06:12:39,569] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:13:04,404] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\urls.py changed, reloading.
[2025-04-22 06:13:04,836] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:13:43,926] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 06:13:47,095] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 69231
[2025-04-22 06:13:47,108] INFO django.server "GET /setpackages/ajax/get-available-transaction-purposes/ HTTP/1.1" 200 40
[2025-04-22 06:13:50,420] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:16:26,883] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 06:16:29,148] INFO django.server "GET /setpackages/setpackages/new/ HTTP/1.1" 200 34024
[2025-04-22 06:16:54,267] INFO django.server "POST /setpackages/setpackages/new/ HTTP/1.1" 302 0
[2025-04-22 06:16:54,277] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4111
[2025-04-22 06:17:06,258] INFO django.server "GET /setpackages/setpackages/6/edit/ HTTP/1.1" 200 34069
[2025-04-22 06:17:11,777] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 06:20:00,596] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 06:20:01,046] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:20:11,670] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\urls.py changed, reloading.
[2025-04-22 06:20:12,123] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:20:17,503] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\urls.py changed, reloading.
[2025-04-22 06:20:17,979] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:21:23,683] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 06:21:24,464] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 71542
[2025-04-22 06:21:24,480] INFO django.server "GET /setpackages/ajax/get-available-transaction-purposes/ HTTP/1.1" 200 55
[2025-04-22 06:21:27,263] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/CUSTOM%20TEST/ HTTP/1.1" 200 16
[2025-04-22 06:21:27,267] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/CUSTOM%20TEST/ HTTP/1.1" 200 16
[2025-04-22 06:21:39,130] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:21:39,134] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:23:39,099] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73358
[2025-04-22 06:23:39,112] INFO django.server "GET /setpackages/ajax/get-available-transaction-purposes/ HTTP/1.1" 200 55
[2025-04-22 06:23:43,118] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/CUSTOM%20TEST/ HTTP/1.1" 200 16
[2025-04-22 06:23:43,124] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/CUSTOM%20TEST/ HTTP/1.1" 200 16
[2025-04-22 06:23:54,986] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:23:54,990] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:24:52,217] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73502
[2025-04-22 06:24:52,233] INFO django.server "GET /setpackages/ajax/get-available-transaction-purposes/ HTTP/1.1" 200 55
[2025-04-22 06:24:56,461] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/CUSTOM%20TEST/ HTTP/1.1" 200 16
[2025-04-22 06:24:56,463] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/CUSTOM%20TEST/ HTTP/1.1" 200 16
[2025-04-22 06:25:11,943] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:25:11,946] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:25:26,657] INFO django.server "GET / HTTP/1.1" 200 6106
[2025-04-22 06:25:29,028] INFO django.server "GET /setpackages/setpackages/list/ HTTP/1.1" 200 4111
[2025-04-22 06:28:44,718] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 40384
[2025-04-22 06:28:51,801] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 40384
[2025-04-22 06:30:44,685] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 40467
[2025-04-22 06:31:43,064] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73489
[2025-04-22 06:31:51,327] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73489
[2025-04-22 06:31:51,772] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73489
[2025-04-22 06:31:51,948] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73489
[2025-04-22 06:34:42,069] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 34405
[2025-04-22 06:39:06,822] INFO django.server "GET /setpackages/ajax/get-available-transaction-purposes/ HTTP/1.1" 200 55
[2025-04-22 06:44:24,451] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\transactions\forms.py changed, reloading.
[2025-04-22 06:44:24,912] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:44:34,500] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\transactions\forms.py changed, reloading.
[2025-04-22 06:44:34,938] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:45:13,016] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\models.py changed, reloading.
[2025-04-22 06:45:13,452] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:45:19,888] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\models.py changed, reloading.
[2025-04-22 06:45:20,279] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:46:23,822] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\transactions\models.py changed, reloading.
[2025-04-22 06:46:24,250] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 06:48:58,745] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73489
[2025-04-22 06:53:13,991] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73489
[2025-04-22 06:53:22,263] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73489
[2025-04-22 06:53:22,700] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73489
[2025-04-22 06:55:43,917] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73494
[2025-04-22 06:56:49,289] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73502
[2025-04-22 06:56:49,308] INFO django.server "GET /setpackages/ajax/get-available-transaction-purposes/ HTTP/1.1" 200 55
[2025-04-22 06:56:51,331] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:56:51,336] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:56:57,708] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/PEME/ HTTP/1.1" 200 20
[2025-04-22 06:56:57,710] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/PEME/ HTTP/1.1" 200 20
[2025-04-22 06:57:14,016] INFO django.server "GET /transactions/ajax/get-company-peme-rate/3/ HTTP/1.1" 200 18
[2025-04-22 06:59:16,075] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/CUSTOM%20TEST/ HTTP/1.1" 200 16
[2025-04-22 06:59:16,075] INFO django.server "GET /setpackages/ajax/get-package-price/?purpose=CUSTOM%20TEST&company_id=3 HTTP/1.1" 200 21
[2025-04-22 06:59:16,079] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/CUSTOM%20TEST/ HTTP/1.1" 200 16
[2025-04-22 06:59:30,117] INFO django.server "GET /setpackages/ajax/get-package-price/?purpose=BUNTIS%20PACKAGE&company_id=3 HTTP/1.1" 200 21
[2025-04-22 06:59:30,119] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:59:30,123] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:59:50,272] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73502
[2025-04-22 06:59:50,290] INFO django.server "GET /setpackages/ajax/get-available-transaction-purposes/ HTTP/1.1" 200 55
[2025-04-22 06:59:55,290] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 06:59:55,294] INFO django.server "GET /setpackages/ajax/get-tests-by-purpose/BUNTIS%20PACKAGE/ HTTP/1.1" 200 29
[2025-04-22 07:02:50,498] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67997
[2025-04-22 07:03:39,881] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67485
[2025-04-22 07:03:42,840] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 67485
[2025-04-22 07:03:52,329] INFO django.server "GET /transactions/transaction/new/ HTTP/1.1" 200 73502
[2025-04-22 07:03:52,348] INFO django.server "GET /setpackages/ajax/get-available-transaction-purposes/ HTTP/1.1" 200 55
[2025-04-22 07:07:30,359] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\transactions\urls.py changed, reloading.
[2025-04-22 07:07:30,761] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 07:08:55,255] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\transactions\urls.py changed, reloading.
[2025-04-22 07:08:55,645] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 07:09:17,388] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\urls.py changed, reloading.
[2025-04-22 07:09:17,800] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 07:10:26,556] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 07:10:26,957] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-04-22 07:10:36,533] INFO django.utils.autoreload C:\Users\Bea\Desktop\personal_projects\mendoza_diagnostic_center_system\mdc_app\setpackages\views.py changed, reloading.
[2025-04-22 07:10:36,968] INFO django.utils.autoreload Watching for file changes with StatReloader
